### ISSUE TITLE
Visual regression testing of all components possible (Challenge once more...)

### ISSUE THREAD

**Issue by yuta-hidaka** [monstar-lab-oss/numba-solidjs#20]
Add storybook.

@yuta-hidaka 
- [x] Button.stories.tsx #17
- [x] Carousel.stories.tsx #35
- [x] Checkbox.stories.tsx #36
- [x] Confirm.stories.tsx #37
- [x] Modal.stories.tsx #38
- ~~FromScratch.stories.tsx~~

@jinmayamashita 
- [x] #22
- [x] #23
- [x] #24
- [x] #25
- [ ] #26 // Direct image import seems not allowed to be used in chromatic, if I do it, chromatic gets stacked.

**Comment by yuta-hidaka** [comment]
We skipped to implement the stories of #26 the reason is https://github.com/monstar-lab-oss/numba-solidjs/issues/20#issue-1836287252.
