### ISSUE TITLE
Maintaining a healthy codebase with easy deliveries

### ISSUE THREAD

**Issue by jinmayamashita** [monstar-lab-oss/numba-solidjs#32]
### Tasks

- [ ] The update of third-party libraries can be automated.

### Tasks

- [x] #20

Needs to fix the Tutorial component.

- [x] Unit testing for the util used in the application is possible.
    - [x] `src/lib/utils/capitalize.ts`
    - [x] `src/lib/utils/dashify.ts`
    - [ ] <strike>`src/lib/utils/figmaNodeHandle.ts`</strike> (won't create tests)
    - [x] `src/lib/utils/figmaRGBA.ts`
    - [x] `src/lib/utils/getMissingSerialNumber.ts`
    - [x] `src/lib/utils/omit.ts`

- [ ] E2E testing for the core functionality of the application is possible. -> (won't create tests) 
    - [ ] <strike>Open the Figma app and test as the user does.</strike>

- [ ] Integration testing 
    - [ ] Try to use Storybook's playtest.
    - [ ] Make tests for each component.

### Tasks

- [ ] Discussing where to perform refactoring. (Also unit testing, E2E testing) @jinmayamashita @yuta-hidaka 

### Tasks

- [ ] Maintain issue templates
- [x] #33

**Comment by jinmayamashita** [comment]
closed by #44
